// Aira Business Kit -- spec: docs/superpowers/specs/2026-09-24-aira-business-kit-design.md
// The Word templates are generated by backend/scripts/kit/build_kit.py into public/kit/.
// Headings carry no numbers: the backend splitter only treats a line as a heading when
// it starts with a capital letter. "[OWNER TO CHECK]" is dropped by the backend's
// scrub_placeholders and shown to the client as a gap, so it never reaches a lead.

// public/ assets are NOT prefixed by basePath -- the /aira prefix must be written out.
const KIT_BASE = "/aira/kit";

export const KIT_INDUSTRIES: { slug: string; label: string }[] = [
  { slug: "coaching", label: "Coaching & education" },
  { slug: "finance", label: "Loans & finance" },
  { slug: "retail", label: "Retail & grocery" },
  { slug: "clinic", label: "Clinic & healthcare" },
  { slug: "real-estate", label: "Real estate" },
  { slug: "interiors", label: "Interiors & home services" },
  { slug: "salon", label: "Salon & spa" },
  { slug: "fitness", label: "Gym & fitness" },
  { slug: "restaurant", label: "Restaurant & food" },
  { slug: "travel", label: "Travel & tours" },
  { slug: "astrology", label: "Astrology & spiritual" },
  { slug: "general", label: "Any other business" },
];

export function kitTemplateUrl(slug: string): string {
  return `${KIT_BASE}/aira-kit-${slug}.docx`;
}

export const KIT_AI_PROMPT = `I'm setting up Aira, an AI assistant that replies to my customers on WhatsApp. Help me write one document about my business that Aira will learn from.

First, use what you already know about my business from our past chats or files. If you don't have enough, interview me: ask ONE question at a time, in simple words, and wait for my answer.

Write the document with EXACTLY these 8 headings, in capital letters, in this order, without numbers:

ABOUT YOUR BUSINESS - name, what you do, since when, where you serve.
WHO YOUR CUSTOMERS ARE - who usually contacts you and what they want most.
HOW A CUSTOMER BUYS FROM YOU - the steps from first message to paying, one per line. End with one line starting "Aira's goal:" - the one next step Aira should push every interested customer toward.
HOW AIRA SHOULD SOUND - tone, how to address people, reply length. (Optional.)
WHAT AIRA MUST NEVER SAY OR PROMISE - one thing per line.
WHEN TO HAND OVER TO A PERSON - which situations, plus the phone number and working hours.
PRODUCTS, SERVICES, PRICES - each item with its exact price, what's included and what's not.
CUSTOMER QUESTIONS AND POLICIES - written as "Q:" and "A:" lines. Include payment, refund, cancellation and delivery rules.

Strict rules:
- Never invent anything. No made-up prices, numbers, phone numbers, links, dates or results.
- If you don't know something and I skip the question, write [OWNER TO CHECK] in its place.
- Copy prices and numbers exactly as I give them.
- Plain English, short lines, no marketing language, no tables.
- Keep it under 2 pages.

When done, show me the full document so I can copy it into a Word file and upload it to Aira.`;
